# Generated by Django 3.0.5 on 2020-05-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hotel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='message',
        ),
        migrations.AddField(
            model_name='hotel',
            name='key',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
